title: Albion
author: Alan Arteaga
email: alanarteagav@gmail.com

description: > # this means to ignore newlines until "show_excerpts:"
  An academic-focused personal webpage.

url: https://alanarteagav.github.io


academia:
  date_format: "%b %d"
  about_you: I love ferns, jazz, cats & computer science.

  social_links:
    github: alanarteagav  
    facebook: alanarteagav
    linkedin: alanarteagav

plugins:
  - jekyll-feed
  - jekyll-seo-tag